require('dotenv').config();
const path = require('path');
const fs = require('fs');
const { sendEmail } = require('./services/emailService');

(async () => {
    const recipient = process.env.TEST_EMAIL || process.env.ADMIN_EMAIL || 'you@example.com';

    try {
        console.log('Sending simple email to', recipient);
        const res = await sendEmail(recipient, 'SES integration test — simple', '<p>This is a test email (no attachments).</p>');
        console.log('Simple send result:', res);
    } catch (err) {
        console.error('Simple send failed:', err);
    }

    // Prepare a small attachment file
    const tmpFile = path.join(__dirname, 'test-attachment.txt');
    try {
        fs.writeFileSync(tmpFile, 'This is a test attachment generated by test-send.js');

        console.log('Sending email with attachment to', recipient);
        const res2 = await sendEmail(
            recipient,
            'SES integration test — with attachment',
            '<p>Please see the attached file.</p>',
            [{ filename: 'test-attachment.txt', path: tmpFile }]
        );
        console.log('Attachment send result:', res2);
    } catch (err) {
        console.error('Attachment send failed:', err);
    } finally {
        try { if (fs.existsSync(tmpFile)) fs.unlinkSync(tmpFile); } catch (e) { }
    }

    process.exit(0);
})();
